#include "qt/CockpitBridge.hpp"
#include "core/TelemetryTrend.hpp"
#include "sim/ScenarioEngine.hpp"
#include "sim/TrainingFaultCatalog.hpp"
#include "telemetry/TelemetryDictionary.hpp"
#include "twin/DigitalTwin.hpp"
#include <QDateTime>
#include <QVariantMap>
#include <algorithm>
#include <chrono>
#include <cmath>
#include <stdexcept>
namespace nexvary::avionics { namespace {QString faultModeText(FaultMode m){switch(m){case FaultMode::Invalidate:return"INVALIDATE";case FaultMode::Override:return"OVERRIDE";case FaultMode::Offset:return"OFFSET";}return"UNKNOWN";}}
CockpitBridge::CockpitBridge(QObject* p):QObject(p),lab_(ScenarioKind::Nominal){refresh(lab_.step());}
QVariantList CockpitBridge::tiles()const{return tiles_;}QVariantList CockpitBridge::sensorRows()const{return sensorRows_;}QVariantList CockpitBridge::eventRows()const{return eventRows_;}QVariantList CockpitBridge::trendRows()const{return trendRows_;}QVariantList CockpitBridge::twinRows()const{return twinRows_;}
QVariantList CockpitBridge::faultPresets()const{QVariantList rows;for(const auto& p:TrainingFaultCatalog::presets(activePlatformId_)){QVariantMap i;i["id"]=QString::fromStdString(p.id);i["label"]=QString::fromStdString(UiLocale::text(language_,p.labelKey));i["detail"]=QString::fromStdString(UiLocale::text(language_,p.detailKey));i["sensor"]=QString::fromStdString(UiLocale::text(language_,p.fault.sensor));i["mode"]=faultModeText(p.fault.mode);rows.push_back(i);}return rows;}
QVariantList CockpitBridge::activeFaultRows()const{QVariantList rows;for(const auto& f:lab_.activeTrainingFaults()){QVariantMap i;i["id"]=QString::fromStdString(f.id);i["sensor"]=QString::fromStdString(UiLocale::text(language_,f.sensor));i["mode"]=faultModeText(f.mode);QString label=QString::fromStdString(f.id);for(const auto& p:TrainingFaultCatalog::presets(activePlatformId_))if(p.fault.id==f.id){label=QString::fromStdString(UiLocale::text(language_,p.labelKey));break;}i["label"]=label;rows.push_back(i);}return rows;}
QStringList CockpitBridge::annunciators()const{return annunciators_;}QString CockpitBridge::scenario()const{return QString::fromUtf8(ScenarioEngine::toString(snapshot_.scenario));}qulonglong CockpitBridge::tick()const noexcept{return snapshot_.tick;}int CockpitBridge::recordedFrames()const noexcept{return static_cast<int>(lab_.recorder().size());}int CockpitBridge::sensorCount()const noexcept{return static_cast<int>(TelemetryDictionary::channels(activePlatformId_).size());}int CockpitBridge::eventCount()const noexcept{return static_cast<int>(lab_.eventLog().size());}int CockpitBridge::trendWindow()const noexcept{return trendWindow_;}int CockpitBridge::twinNominalCount()const noexcept{return twinNominalCount_;}int CockpitBridge::twinDegradedCount()const noexcept{return twinDegradedCount_;}int CockpitBridge::twinFaultCount()const noexcept{return twinFaultCount_;}int CockpitBridge::twinUnknownCount()const noexcept{return twinUnknownCount_;}int CockpitBridge::activeTrainingFaultCount()const noexcept{return static_cast<int>(lab_.activeTrainingFaults().size());}
int CockpitBridge::activeAlertCount()const noexcept{int c=0;for(const auto& a:snapshot_.alerts)if(a.active)++c;return c;}bool CockpitBridge::replayMode()const noexcept{return replayMode_;}bool CockpitBridge::replayPaused()const noexcept{return replayPaused_;}int CockpitBridge::replayIndex()const noexcept{return replayIndex_;}int CockpitBridge::replayMaximum()const noexcept{return lab_.recorder().size()?static_cast<int>(lab_.recorder().size()-1):0;}QString CockpitBridge::replayTime()const{const auto f=lab_.recorder().frame(static_cast<std::size_t>(std::clamp(replayIndex_,0,replayMaximum())));return f?QStringLiteral("T+%1 s").arg(static_cast<double>(f->simTime.count())/1000.0,0,'f',1):QStringLiteral("T+0.0 s");}QString CockpitBridge::language()const{return QString::fromStdString(UiLocale::code(language_));}bool CockpitBridge::rtl()const noexcept{return UiLocale::isRtl(language_);}QStringList CockpitBridge::scenarios()const{QStringList r;for(const auto& n:ScenarioEngine::names())r.push_back(QString::fromStdString(n));return r;}
void CockpitBridge::step(){if(replayMode_){if(!replayPaused_&&replayIndex_<replayMaximum())++replayIndex_;showReplayFrame();return;}refresh(lab_.step());}void CockpitBridge::resetLab(){replayMode_=replayPaused_=false;replayIndex_=0;lab_.reset();refresh(lab_.step());}void CockpitBridge::setScenario(const QString& n){try{replayMode_=replayPaused_=false;replayIndex_=0;lab_.setScenario(ScenarioEngine::fromName(n.toStdString()));lab_.reset();refresh(lab_.step());}catch(const std::invalid_argument&){} }void CockpitBridge::setLanguage(const QString& c){const auto n=UiLocale::fromCode(c.toStdString());if(n==language_)return;language_=n;refresh(snapshot_);emit languageChanged();}QString CockpitBridge::text(const QString& k)const{return QString::fromStdString(UiLocale::text(language_,k.toStdString()));}
void CockpitBridge::setReplayMode(bool e){if(e&&lab_.recorder().size()==0)return;replayMode_=e;replayPaused_=e;if(e){replayIndex_=0;showReplayFrame();}else refresh(lab_.snapshot());}void CockpitBridge::setReplayPaused(bool p){if(!replayMode_||replayPaused_==p)return;replayPaused_=p;emit dataChanged();}void CockpitBridge::seekReplay(int i){if(!replayMode_)return;replayIndex_=std::clamp(i,0,replayMaximum());showReplayFrame();}void CockpitBridge::setTrendWindow(int f){const int n=std::clamp(f,0,5000);if(n==trendWindow_)return;trendWindow_=n;refreshTrends();emit dataChanged();}void CockpitBridge::applyTrainingFault(const QString& id){replayMode_=replayPaused_=false;if(!lab_.applyTrainingFault(activePlatformId_,id.toStdString()))return;refresh(lab_.step());}void CockpitBridge::clearTrainingFaults(){replayMode_=replayPaused_=false;lab_.clearTrainingFaults();refresh(lab_.step());}
void CockpitBridge::showReplayFrame(){const auto f=lab_.recorder().frame(static_cast<std::size_t>(replayIndex_));if(!f)return;LabSnapshot r=snapshot_;r.tick=f->sequence;r.simTime=f->simTime;r.sensors=f->sensors;r.issues.clear();r.alerts.clear();refresh(r);}
void CockpitBridge::refreshTrends(){trendRows_.clear();const auto ts=TelemetryTrendAnalyzer::analyze(lab_.recorder().frames(),static_cast<std::size_t>(trendWindow_));for(const auto&[name,t]:ts){if(!TelemetryDictionary::find(activePlatformId_,name))continue;QVariantMap i;i["id"]=QString::fromStdString(name);i["label"]=QString::fromStdString(UiLocale::text(language_,name));i["unit"]=QString::fromStdString(t.unit);i["samples"]=static_cast<qulonglong>(t.samples);i["valid"]=static_cast<qulonglong>(t.validSamples);i["invalid"]=static_cast<qulonglong>(t.invalidSamples);i["missing"]=static_cast<qulonglong>(t.missingSamples);i["minimum"]=t.minimum;i["maximum"]=t.maximum;i["mean"]=t.mean;i["latest"]=t.latest;i["delta"]=t.delta;i["slope"]=t.slopePerSecond;i["hasValid"]=t.hasValidSamples;const auto w=t.samples+t.missingSamples;const double q=w?100.0*static_cast<double>(t.validSamples)/static_cast<double>(w):0.0;i["quality"]=std::round(q*10.0)/10.0;trendRows_.push_back(i);}}
void CockpitBridge::refreshTwin(){twinRows_.clear();const auto t=DigitalTwinModel::build(activePlatformId_,snapshot_.sensors,snapshot_.issues);twinNominalCount_=static_cast<int>(t.nominalCount);twinDegradedCount_=static_cast<int>(t.degradedCount);twinFaultCount_=static_cast<int>(t.faultCount);twinUnknownCount_=static_cast<int>(t.unknownCount);for(const auto& s:t.subsystems){QVariantMap i;i["id"]=QString::fromStdString(s.id);i["label"]=QString::fromStdString(UiLocale::text(language_,s.id));i["state"]=QString::fromLatin1(to_string(s.state));i["expected"]=static_cast<qulonglong>(s.expectedChannels);i["observed"]=static_cast<qulonglong>(s.observedChannels);i["valid"]=static_cast<qulonglong>(s.validChannels);i["issues"]=static_cast<qulonglong>(s.issueCount);i["health"]=s.healthPercent;twinRows_.push_back(i);}}
void CockpitBridge::refresh(const LabSnapshot& s){snapshot_=s;const auto page=viewModel_.build(snapshot_);tiles_.clear();for(const auto& t:page.tiles){QVariantMap i;i["id"]=QString::fromStdString(t.id);i["label"]=QString::fromStdString(UiLocale::text(language_,t.id));i["value"]=QString::fromStdString(t.value);i["state"]=QString::fromStdString(t.state);tiles_.push_back(i);}sensorRows_.clear();for(const auto&[name,sample]:snapshot_.sensors){if(!TelemetryDictionary::find(activePlatformId_,name))continue;QVariantMap i;i["id"]=QString::fromStdString(name);i["label"]=QString::fromStdString(UiLocale::text(language_,name));i["value"]=sample.value;i["unit"]=QString::fromStdString(sample.unit);i["valid"]=sample.valid;sensorRows_.push_back(i);}eventRows_.clear();for(const auto&e:lab_.eventLog().snapshot()){QVariantMap i;i["severity"]=QString::fromLatin1(to_string(e.severity));i["source"]=QString::fromStdString(e.source);i["message"]=QString::fromStdString(e.message);const auto ms=std::chrono::duration_cast<std::chrono::milliseconds>(e.timestamp.time_since_epoch()).count();i["epochMs"]=static_cast<qlonglong>(ms);i["time"]=QDateTime::fromMSecsSinceEpoch(static_cast<qint64>(ms)).toString(QStringLiteral("HH:mm:ss.zzz"));eventRows_.push_back(i);}refreshTrends();refreshTwin();annunciators_.clear();if(replayMode_)annunciators_.push_back(QString::fromStdString(UiLocale::text(language_,"replay_mode")));for(const auto&a:page.annunciators)annunciators_.push_back(QString::fromStdString(a=="SYSTEMS NOMINAL"?UiLocale::text(language_,"systems_nominal"):a));emit dataChanged();}
} // namespace nexvary::avionics