#include "verify/SessionVerifier.hpp"
#include "telemetry/TelemetryDictionary.hpp"
#include <cmath>
#include <utility>
namespace nexvary::avionics {
namespace {void add(VerificationSummary& s,VerificationLevel l,std::string code,std::string message,std::size_t index){s.findings.push_back({l,std::move(code),std::move(message),index});if(l==VerificationLevel::Warning)++s.warningCount;if(l==VerificationLevel::Error)++s.errorCount;}}
VerificationSummary SessionVerifier::verify(const std::vector<TelemetryFrame>& frames){VerificationSummary out;if(frames.empty()){add(out,VerificationLevel::Error,"EMPTY_SESSION","session contains no telemetry frames",0);return out;}for(std::size_t i=0;i<frames.size();++i){const auto& frame=frames[i];if(i>0){if(frame.sequence<=frames[i-1].sequence)add(out,VerificationLevel::Error,"SEQUENCE_ORDER","frame sequence is not strictly increasing",i);if(frame.simTime<=frames[i-1].simTime)add(out,VerificationLevel::Error,"TIME_ORDER","simulation time is not strictly increasing",i);}for(const auto& def:TelemetryDictionary::channels()){const auto it=frame.sensors.find(def.id);if(it==frame.sensors.end()){if(def.required)add(out,VerificationLevel::Error,"MISSING_CHANNEL","required telemetry channel missing: "+def.id,i);continue;}if(!std::isfinite(it->second.value)){add(out,VerificationLevel::Error,"NONFINITE_VALUE","non-finite telemetry value: "+def.id,i);continue;}const auto validation=TelemetryDictionary::validate(def.id,it->second);if(!validation.unitMatches)add(out,VerificationLevel::Error,"UNIT_MISMATCH","telemetry unit mismatch: "+def.id,i);if(!validation.inEngineeringRange)add(out,VerificationLevel::Warning,"ENGINEERING_RANGE","telemetry outside defensive engineering range: "+def.id,i);if(!it->second.valid)add(out,VerificationLevel::Warning,"INVALID_SAMPLE","sample marked invalid: "+def.id,i);}}return out;}
const char* to_string(VerificationLevel level) noexcept{switch(level){case VerificationLevel::Info:return "INFO";case VerificationLevel::Warning:return "WARNING";case VerificationLevel::Error:return "ERROR";}return "UNKNOWN";}
} // namespace nexvary::avionics
