.pragma library

var D = {
    ar: {label:"إدارة القوة الجوية", title:"إدارة القوة الجوية والجاهزية", subtitle:"القواعد والسرب والجاهزية والتدريب والصيانة والطقس والتقارير — بيانات تدريبية اصطناعية", bases:"القواعد وحالة المطارات", squadrons:"الأسراب وتوزيع الأسطول", training:"جدول التدريب", maintenance:"تخطيط الصيانة", crew:"جاهزية الأطقم", weather:"الطقس وحالة المطار", reports:"التقارير التنفيذية", planning:"تخطيط الأسطول", boundary:"تخطيط وتدريب وتحليل فقط — لا أوامر تشغيلية أو توجيه أسلحة"},
    en: {label:"AIR FORCE MANAGEMENT", title:"AIR FORCE MANAGEMENT & READINESS", subtitle:"Bases, squadrons, readiness, training, maintenance, weather and executive reporting — synthetic training data", bases:"BASES & AIRFIELD STATUS", squadrons:"SQUADRONS & FLEET ALLOCATION", training:"TRAINING SCHEDULE", maintenance:"MAINTENANCE PLANNING", crew:"CREW READINESS", weather:"WEATHER & AIRFIELD", reports:"EXECUTIVE REPORTS", planning:"FLEET PLANNING", boundary:"Planning, training and analysis only — no operational orders or weapons direction"},
    tr: {label:"HAVA KUVVETİ YÖNETİMİ", title:"HAVA KUVVETİ YÖNETİMİ VE HAZIRLIK", subtitle:"Üsler, filolar, hazırlık, eğitim, bakım, hava durumu ve yönetici raporları — sentetik eğitim verileri", bases:"ÜSLER VE HAVAALANI DURUMU", squadrons:"FİLOLAR VE FİLO DAĞILIMI", training:"EĞİTİM TAKVİMİ", maintenance:"BAKIM PLANLAMA", crew:"MÜRETTEBAT HAZIRLIĞI", weather:"HAVA DURUMU VE MEYDAN", reports:"YÖNETİCİ RAPORLARI", planning:"FİLO PLANLAMA", boundary:"Yalnızca planlama, eğitim ve analiz — operasyonel emir veya silah yönlendirmesi yok"},
    es: {label:"GESTIÓN DE FUERZA AÉREA", title:"GESTIÓN Y DISPONIBILIDAD DE LA FUERZA AÉREA", subtitle:"Bases, escuadrones, disponibilidad, entrenamiento, mantenimiento, meteorología e informes — datos sintéticos", bases:"BASES Y ESTADO DE AERÓDROMOS", squadrons:"ESCUADRONES Y ASIGNACIÓN DE FLOTA", training:"PROGRAMA DE ENTRENAMIENTO", maintenance:"PLANIFICACIÓN DE MANTENIMIENTO", crew:"DISPONIBILIDAD DE TRIPULACIONES", weather:"METEOROLOGÍA Y AERÓDROMOS", reports:"INFORMES EJECUTIVOS", planning:"PLANIFICACIÓN DE FLOTA", boundary:"Solo planificación, entrenamiento y análisis — sin órdenes operativas ni dirección de armas"},
    de: {label:"LUFTSTREITKRÄFTE-MANAGEMENT", title:"LUFTSTREITKRÄFTE-MANAGEMENT & BEREITSCHAFT", subtitle:"Basen, Staffeln, Bereitschaft, Training, Wartung, Wetter und Berichte — synthetische Trainingsdaten", bases:"BASEN & FLUGPLATZSTATUS", squadrons:"STAFFELN & FLOTTENZUWEISUNG", training:"TRAININGSPLAN", maintenance:"WARTUNGSPLANUNG", crew:"BESATZUNGSBEREITSCHAFT", weather:"WETTER & FLUGPLATZ", reports:"EXECUTIVE REPORTS", planning:"FLOTTENPLANUNG", boundary:"Nur Planung, Training und Analyse — keine Einsatzbefehle oder Waffensteuerung"},
    it: {label:"GESTIONE FORZA AEREA", title:"GESTIONE E PRONTEZZA DELLA FORZA AEREA", subtitle:"Basi, squadriglie, prontezza, addestramento, manutenzione, meteo e rapporti — dati sintetici", bases:"BASI E STATO AEROPORTI", squadrons:"SQUADRIGLIE E ALLOCAZIONE FLOTTA", training:"PROGRAMMA ADDESTRAMENTO", maintenance:"PIANIFICAZIONE MANUTENZIONE", crew:"PRONTEZZA EQUIPAGGI", weather:"METEO E AEROPORTI", reports:"RAPPORTI ESECUTIVI", planning:"PIANIFICAZIONE FLOTTA", boundary:"Solo pianificazione, addestramento e analisi — nessun ordine operativo o direzione armi"},
    fr: {label:"GESTION DE LA FORCE AÉRIENNE", title:"GESTION ET DISPONIBILITÉ DE LA FORCE AÉRIENNE", subtitle:"Bases, escadrons, disponibilité, formation, maintenance, météo et rapports — données synthétiques", bases:"BASES ET ÉTAT DES AÉRODROMES", squadrons:"ESCADRONS ET AFFECTATION DE FLOTTE", training:"PROGRAMME D’ENTRAÎNEMENT", maintenance:"PLANIFICATION MAINTENANCE", crew:"DISPONIBILITÉ DES ÉQUIPAGES", weather:"MÉTÉO ET AÉRODROMES", reports:"RAPPORTS EXÉCUTIFS", planning:"PLANIFICATION DE FLOTTE", boundary:"Planification, formation et analyse uniquement — aucun ordre opérationnel ni guidage d’armes"},
    ur: {label:"فضائی فورس انتظام", title:"فضائی فورس انتظام اور تیاری", subtitle:"اڈے، اسکواڈرن، تیاری، تربیت، دیکھ بھال، موسم اور انتظامی رپورٹس — مصنوعی تربیتی ڈیٹا", bases:"اڈے اور ہوائی اڈے کی حالت", squadrons:"اسکواڈرن اور بیڑے کی تقسیم", training:"تربیتی شیڈول", maintenance:"دیکھ بھال کی منصوبہ بندی", crew:"عملے کی تیاری", weather:"موسم اور ہوائی اڈہ", reports:"انتظامی رپورٹس", planning:"بیڑے کی منصوبہ بندی", boundary:"صرف منصوبہ بندی، تربیت اور تجزیہ — کوئی عملی حکم یا ہتھیاروں کی رہنمائی نہیں"},
    fa: {label:"مدیریت نیروی هوایی", title:"مدیریت و آمادگی نیروی هوایی", subtitle:"پایگاه‌ها، اسکادران‌ها، آمادگی، آموزش، نگهداری، هواشناسی و گزارش‌ها — داده‌های آموزشی مصنوعی", bases:"پایگاه‌ها و وضعیت فرودگاه", squadrons:"اسکادران‌ها و تخصیص ناوگان", training:"برنامه آموزش", maintenance:"برنامه‌ریزی نگهداری", crew:"آمادگی خدمه", weather:"هواشناسی و فرودگاه", reports:"گزارش‌های اجرایی", planning:"برنامه‌ریزی ناوگان", boundary:"فقط برنامه‌ریزی، آموزش و تحلیل — بدون دستور عملیاتی یا هدایت تسلیحات"},
    ru: {label:"УПРАВЛЕНИЕ ВВС", title:"УПРАВЛЕНИЕ И ГОТОВНОСТЬ ВВС", subtitle:"Базы, эскадрильи, готовность, обучение, обслуживание, погода и отчёты — синтетические данные", bases:"БАЗЫ И СОСТОЯНИЕ АЭРОДРОМОВ", squadrons:"ЭСКАДРИЛЬИ И РАСПРЕДЕЛЕНИЕ ПАРКА", training:"ГРАФИК ОБУЧЕНИЯ", maintenance:"ПЛАНИРОВАНИЕ ТО", crew:"ГОТОВНОСТЬ ЭКИПАЖЕЙ", weather:"ПОГОДА И АЭРОДРОМЫ", reports:"ИСПОЛНИТЕЛЬНЫЕ ОТЧЁТЫ", planning:"ПЛАНИРОВАНИЕ ПАРКА", boundary:"Только планирование, обучение и анализ — без оперативных приказов и управления оружием"}
}

function row(code) { return D[code] || D.en }
function label(code) { return row(code).label }
function title(code) { return row(code).title }
function subtitle(code) { return row(code).subtitle }
function bases(code) { return row(code).bases }
function squadrons(code) { return row(code).squadrons }
function training(code) { return row(code).training }
function maintenance(code) { return row(code).maintenance }
function crew(code) { return row(code).crew }
function weather(code) { return row(code).weather }
function reports(code) { return row(code).reports }
function planning(code) { return row(code).planning }
function boundary(code) { return row(code).boundary }
