.pragma library

function code(code, system, severity, title, meaning, cause, isolation, recovery, sensor) {
    return {"code":code,"system":system,"severity":severity,"title":title,"meaning":meaning,"cause":cause,"isolation":isolation,"recovery":recovery,"sensor":sensor}
}

function catalog() {
    return [
        code("NXD-PWR-101", "POWER", "WARNING", "Bus Voltage Below Training Envelope", "Main simulated electrical bus below nominal training range.", "Power transient, low-power preset, or invalid voltage sample.", "Validate bus_voltage_v; review trend; correlate with power twin and events.", "Restore stable nominal voltage and confirm power twin NOMINAL.", "bus_voltage_v"),
        code("NXD-PWR-102", "POWER", "FAULT", "Bus Voltage Above Training Envelope", "Main simulated bus exceeds configured upper training limit.", "Injected offset, synthetic regulator anomaly, or corrupted sample.", "Compare current bus_voltage_v with prior frames and dictionary range.", "Return voltage to nominal band and pass two consecutive verification frames.", "bus_voltage_v"),
        code("NXD-PWR-103", "POWER", "WARNING", "Source Load Imbalance", "Synthetic power-source loading is uneven beyond training tolerance.", "Scenario imbalance, synthetic source loss, or stale load estimate.", "Review source/load indicators and correlate with bus trend and events.", "Rebalance synthetic sources and verify stable bus quality.", "bus_voltage_v"),
        code("NXD-PWR-104", "POWER", "FAULT", "Backup Power Source Unavailable", "Configured backup electrical source is unavailable in the training model.", "Injected source outage, invalid readiness state, or scenario transition.", "Confirm source state, related alerts, and timeline ordering.", "Restore backup-source readiness and verify no dependent power findings.", "bus_voltage_v"),
        code("NXD-CMP-201", "COMPUTE", "WARNING", "Compute Thermal Excursion", "Simulated compute temperature is above its training threshold.", "Thermal-rise scenario, compute-hot preset, or abnormal temperature trend.", "Review cpu_temp_c quality, slope, twin state and recent warnings.", "Remove synthetic thermal condition and confirm downward stable trend.", "cpu_temp_c"),
        code("NXD-CMP-202", "COMPUTE", "WARNING", "Processing Load Saturation", "Synthetic processing load remains near its configured ceiling.", "High-workload scenario, repeated event processing, or test stress.", "Correlate processing indicators with recorder rate and alert timing.", "Reduce synthetic workload and verify sustained margin below threshold.", ""),
        code("NXD-CMP-203", "COMPUTE", "FAULT", "Watchdog Recovery Event", "Training compute node required a watchdog-style recovery cycle.", "Injected compute stall, timing overrun, or synthetic service hang.", "Inspect event chronology around the recovery and check data gaps.", "Verify stable post-recovery operation with no repeated watchdog events.", ""),
        code("NXD-CMP-204", "COMPUTE", "WARNING", "Runtime Configuration Mismatch", "Active training configuration differs from the expected run profile.", "Profile mismatch, stale configuration, or replay/session inconsistency.", "Compare run profile, scenario, provider identity and release manifest.", "Reload a consistent profile and verify configuration evidence matches.", ""),
        code("NXD-FLT-301", "FLIGHT SENSORS", "FAULT", "Attitude Channel Unavailable", "One or more simulated attitude channels are invalid or unavailable.", "Sensor-dropout scenario, IMU dropout preset, or invalid sample.", "Check imu_pitch_deg and imu_roll_deg validity and quality counters.", "Restore valid synthetic IMU samples and verify both channels nominal.", "imu_pitch_deg"),
        code("NXD-FLT-302", "FLIGHT SENSORS", "WARNING", "Attitude Channel Disagreement", "Synthetic attitude channels disagree beyond configured training tolerance.", "Injected offset, inconsistent replay frame, or one degraded channel.", "Compare pitch/roll deltas, recent trends and flight-sensor twin state.", "Restore coherent attitude channels and verify disagreement clears.", "imu_roll_deg"),
        code("NXD-FLT-303", "FLIGHT SENSORS", "FAULT", "Altitude Channel Invalid", "Synthetic altitude channel is invalid or outside declared dictionary bounds.", "Dropout, corrupted sample, or injected out-of-range value.", "Validate altitude_m quality, range and timeline continuity.", "Restore valid altitude samples and pass dictionary/range verification.", "altitude_m"),
        code("NXD-FLT-304", "FLIGHT SENSORS", "FAULT", "Airspeed Channel Invalid", "Synthetic airspeed is unavailable, stale, or outside training bounds.", "Dropout, frozen sample, replay discontinuity, or injected anomaly.", "Inspect airspeed_kph validity, age, delta and correlated events.", "Restore valid changing airspeed data and verify sensor twin recovery.", "airspeed_kph"),
        code("NXD-HYD-401", "HYDRAULICS", "WARNING", "Hydraulic Pressure Degraded", "Simulated hydraulic pressure is outside the preferred training band.", "Scenario degradation, invalid sample, or synthetic subsystem fault.", "Inspect hydraulic_pressure_pct value, quality, delta and twin state.", "Return pressure to stable nominal band and twin NOMINAL.", "hydraulic_pressure_pct"),
        code("NXD-HYD-402", "HYDRAULICS", "WARNING", "Hydraulic Pressure Unstable", "Synthetic pressure oscillates faster than expected for the training profile.", "Injected oscillation, noisy channel, or discontinuous replay data.", "Review rolling min/max, delta, slope and event correlation.", "Stabilize the synthetic channel and verify reduced variance.", "hydraulic_pressure_pct"),
        code("NXD-HYD-403", "HYDRAULICS", "WARNING", "Hydraulic Thermal Margin Reduced", "Training model indicates reduced hydraulic thermal margin.", "Synthetic heat-load condition or scenario stress.", "Correlate subsystem state with time window and any pressure degradation.", "Remove heat-load condition and confirm stable recovery trend.", ""),
        code("NXD-HYD-404", "HYDRAULICS", "FAULT", "Hydraulic Sensor Quality Fault", "Hydraulic evidence channel quality is insufficient for diagnosis.", "Invalid, missing, or stale pressure samples.", "Check quality counters and identify first invalid frame in replay.", "Restore continuous valid samples before accepting hydraulic diagnosis.", "hydraulic_pressure_pct"),
        code("NXD-FUL-501", "FUEL", "WARNING", "Fuel Quantity Channel Mismatch", "Synthetic fuel quantity is inconsistent with expected training progression.", "Injected offset, frame discontinuity, or abnormal trend.", "Compare fuel_level_pct with prior frames, delta and recorder continuity.", "Restore continuous nominal fuel signal and clear mismatch.", "fuel_level_pct"),
        code("NXD-FUL-502", "FUEL", "WARNING", "Fuel Consumption Trend Anomaly", "Synthetic fuel quantity changes at an unexpected training rate.", "Injected rate change, scenario stress, or replay inconsistency.", "Review slope and recent frame-to-frame deltas for fuel_level_pct.", "Return to expected training trend and verify stable slope.", "fuel_level_pct"),
        code("NXD-FUL-503", "FUEL", "FAULT", "Fuel Quantity Channel Unavailable", "Fuel quantity evidence is missing or invalid in the current frame.", "Sensor dropout, corrupted sample, or session gap.", "Check channel validity and first missing frame in timeline.", "Restore valid fuel samples and verify evidence continuity.", "fuel_level_pct"),
        code("NXD-FUL-504", "FUEL", "WARNING", "Fuel State Coherence Deviation", "Fuel state conflicts with the expected scenario or recorded context.", "Profile mismatch, synthetic offset, or replay/session mismatch.", "Compare scenario identity, run profile and fuel trend together.", "Use a coherent run/session and verify state consistency.", "fuel_level_pct"),
        code("NXD-DAT-601", "DATA", "FAULT", "Telemetry Sequence Integrity Fault", "Training session contains missing, invalid or non-monotonic telemetry.", "Corrupted session, missing frame, invalid sample, or order failure.", "Run verification and identify first invalid frame/channel.", "Regenerate or load a valid session and pass sequence checks.", ""),
        code("NXD-DAT-602", "DATA", "FAULT", "Timestamp Discontinuity", "Simulation timestamps are non-monotonic or contain a large discontinuity.", "Corrupted archive, replay splice, or invalid session metadata.", "Inspect timeline around first discontinuity and compare frame sequence.", "Use continuous deterministic timing and pass timeline verification.", ""),
        code("NXD-DAT-603", "DATA", "WARNING", "Telemetry Channel Stale", "A channel has stopped changing or updating within expected training cadence.", "Frozen synthetic source, provider stall, or replay pause mismatch.", "Check sample age, update cadence and provider state.", "Restore expected update cadence and confirm fresh consecutive samples.", ""),
        code("NXD-DAT-604", "DATA", "FAULT", "Telemetry Schema Mismatch", "Loaded telemetry does not match the expected versioned training schema.", "Old export, incompatible session, or malformed synthetic data.", "Compare schema version, channel IDs and release manifest.", "Load or regenerate data using the supported schema version.", ""),
        code("NXD-NAV-701", "NAVIGATION", "WARNING", "Navigation Sensor Disagreement", "Simulated navigation-related channels disagree beyond training tolerance.", "Synthetic offset, dropout, or inconsistent replay frame.", "Correlate altitude/attitude channels, quality and current scenario.", "Restore coherent synthetic channels and confirm twin NOMINAL.", "altitude_m"),
        code("NXD-NAV-702", "NAVIGATION", "WARNING", "Position Quality Degraded", "Synthetic navigation quality metric falls below preferred training level.", "Injected quality reduction, stale source, or provider degradation.", "Inspect source quality, freshness and correlated event timing.", "Restore valid high-quality synthetic navigation evidence.", ""),
        code("NXD-NAV-703", "NAVIGATION", "WARNING", "Heading Consistency Deviation", "Synthetic heading context is inconsistent with related attitude progression.", "Injected offset or mismatched replay/session context.", "Compare heading context with attitude trend and scenario phase.", "Restore coherent navigation context and verify deviation clears.", "imu_roll_deg"),
        code("NXD-NAV-704", "NAVIGATION", "FAULT", "Altitude Coherence Failure", "Altitude evidence conflicts with the expected navigation state.", "Invalid altitude sample, corrupted frame, or synthetic source mismatch.", "Check altitude_m validity, range, timeline and provider identity.", "Restore coherent altitude evidence and pass navigation verification.", "altitude_m"),
        code("NXD-REC-801", "RECORDER", "FAULT", "Recorder Continuity Failure", "Training recorder cannot provide a continuous evidence chain.", "Empty recording, frame discontinuity, invalid time order, or corruption.", "Check frame count, monotonicity and verification evidence.", "Create a fresh valid recording and pass verification gates.", ""),
        code("NXD-REC-802", "RECORDER", "FAULT", "Archive Checksum Mismatch", "Recorded archive integrity check does not match expected checksum.", "Corrupted archive, incomplete copy, or modified training file.", "Inspect archive verification result before using replay evidence.", "Use a valid archive whose integrity checks pass.", ""),
        code("NXD-REC-803", "RECORDER", "WARNING", "Replay Index Out of Range", "Requested replay position falls outside the recorded frame set.", "Stale UI index, truncated session, or inconsistent frame count.", "Compare requested index with recorder size and session metadata.", "Seek within valid bounds and confirm synchronized replay state.", ""),
        code("NXD-REC-804", "RECORDER", "WARNING", "Evidence Export Incomplete", "A requested report/session export lacks expected evidence elements.", "Interrupted export, missing frames, or report generation mismatch.", "Compare export contents with session and release verifier expectations.", "Regenerate export and verify required evidence is present.", ""),
        code("NXD-COM-901", "COMMUNICATIONS", "WARNING", "Data Link Quality Degraded", "Synthetic communications quality is below preferred training threshold.", "Injected link degradation, stale source, or scenario condition.", "Review link-quality evidence and event correlation.", "Restore nominal synthetic link quality and verify stable status.", ""),
        code("NXD-COM-902", "COMMUNICATIONS", "WARNING", "Message Latency Elevated", "Synthetic message delivery latency exceeds the configured training target.", "Injected delay, processing load, or provider timing anomaly.", "Correlate latency with compute load and timeline events.", "Remove delay condition and verify latency returns within target.", ""),
        code("NXD-COM-903", "COMMUNICATIONS", "FAULT", "Communications Channel Unavailable", "A simulated communications channel is unavailable for the current run.", "Injected channel loss, provider outage, or configuration mismatch.", "Check channel state, provider identity and event chronology.", "Restore synthetic channel availability and verify nominal status.", ""),
        code("NXD-COM-904", "COMMUNICATIONS", "FAULT", "Communications Synchronization Lost", "Synthetic communications timing is no longer synchronized with run time.", "Provider timing drift, replay mismatch, or injected sync fault.", "Compare communications timestamps with unified timeline.", "Re-establish deterministic timing and verify synchronization.", ""),
        code("NXD-ECS-1001", "ENVIRONMENTAL", "WARNING", "Cabin Temperature Outside Training Envelope", "Synthetic environmental temperature exceeds configured training limits.", "Injected heat/cool condition, stale sample, or scenario stress.", "Check temperature evidence, trend and environmental state.", "Return temperature to nominal envelope and verify stable trend.", ""),
        code("NXD-ECS-1002", "ENVIRONMENTAL", "WARNING", "Pressure State Anomaly", "Synthetic environmental pressure state deviates from expected profile.", "Injected pressure condition or inconsistent scenario state.", "Correlate pressure state with scenario phase and event timeline.", "Restore expected synthetic pressure state and verify recovery.", ""),
        code("NXD-ECS-1003", "ENVIRONMENTAL", "WARNING", "Cooling Performance Degraded", "Training model indicates insufficient cooling margin.", "Synthetic cooling-load increase or compute thermal coupling.", "Correlate cooling state with cpu_temp_c trend and alerts.", "Restore cooling margin and confirm compute temperature stabilizes.", "cpu_temp_c"),
        code("NXD-ECS-1004", "ENVIRONMENTAL", "FAULT", "Environmental Sensor Invalid", "Environmental diagnostic evidence is invalid or unavailable.", "Dropout, stale sample, or malformed synthetic telemetry.", "Identify invalid source and confirm related data-quality counters.", "Restore valid evidence before accepting environmental diagnosis.", ""),
        code("NXD-ACT-1101", "ACTUATION", "FAULT", "Command Feedback Mismatch", "Synthetic actuator feedback does not match the commanded training state.", "Injected response fault, sensor offset, or timing mismatch.", "Compare command state, feedback state and event sequence.", "Restore coherent feedback and verify mismatch remains cleared.", ""),
        code("NXD-ACT-1102", "ACTUATION", "WARNING", "Actuator Response Slow", "Synthetic actuator response exceeds the configured training response time.", "Injected lag, provider delay, or scenario degradation.", "Measure response timing against command event in unified timeline.", "Remove lag condition and verify response meets training target.", ""),
        code("NXD-ACT-1103", "ACTUATION", "FAULT", "Position Evidence Invalid", "Synthetic actuator position evidence is missing or invalid.", "Sensor dropout, stale feedback, or malformed sample.", "Check feedback validity and locate first invalid frame.", "Restore valid position evidence and verify continuous updates.", ""),
        code("NXD-ACT-1104", "ACTUATION", "WARNING", "Control Symmetry Deviation", "Paired synthetic control responses are not symmetric within tolerance.", "Injected offset, timing difference, or inconsistent feedback.", "Compare paired response values and timing over the same window.", "Restore matched response behavior and clear deviation.", ""),
        code("NXD-ASR-1201", "ASSURANCE", "FAULT", "Verification Gate Failed", "One or more configured verification gates did not pass.", "Invalid session evidence, failed expectation, or inconsistent output.", "Open Verification Center and identify the first failed gate.", "Correct the underlying evidence and rerun verification to PASS.", ""),
        code("NXD-ASR-1202", "ASSURANCE", "FAULT", "Evidence Chain Incomplete", "Required training evidence cannot be traced across the full run.", "Missing event, frame gap, incomplete export, or session corruption.", "Correlate recorder, timeline, events and report references.", "Regenerate a complete run with continuous evidence chain.", ""),
        code("NXD-ASR-1203", "ASSURANCE", "WARNING", "Digital Twin Consistency Mismatch", "Digital Twin state disagrees with available telemetry evidence.", "Stale twin state, incomplete channels, or scenario transition.", "Compare twin inputs with sensor validity and current event sequence.", "Restore coherent inputs and confirm twin state matches evidence.", ""),
        code("NXD-ASR-1204", "ASSURANCE", "FAULT", "Verification Report Schema Mismatch", "Verification report does not match the supported report schema.", "Older report, malformed export, or incompatible tool version.", "Check report schema version and release identity.", "Regenerate report with current supported version and revalidate.", "")
    ]
}

function systems() {
    return ["ALL","POWER","COMPUTE","FLIGHT SENSORS","HYDRAULICS","FUEL","DATA","NAVIGATION","RECORDER","COMMUNICATIONS","ENVIRONMENTAL","ACTUATION","ASSURANCE"]
}
