#include "sim/ScenarioEngine.hpp"
#include <algorithm>
#include <cmath>
#include <stdexcept>
namespace nexvary::avionics {
ScenarioEngine::ScenarioEngine(ScenarioKind kind):kind_(kind){} void ScenarioEngine::setScenario(ScenarioKind kind){kind_=kind;} ScenarioKind ScenarioEngine::scenario()const noexcept{return kind_;}
void ScenarioEngine::step(const SimulationClock& clock,SensorBus& bus,FaultInjector& faults)const{const double t=static_cast<double>(clock.elapsed().count())/1000.0;const double wave=std::sin(t*.35);
 bus.publish("cpu_temp_c",{58.0+wave*2.5,"C",true});bus.publish("bus_voltage_v",{27.2+std::sin(t*.2)*.25,"V",true});bus.publish("imu_pitch_deg",{std::sin(t*.45)*4.0,"deg",true});bus.publish("imu_roll_deg",{std::sin(t*.31)*7.0,"deg",true});bus.publish("altitude_m",{2400.0+std::sin(t*.08)*120.0,"m",true});bus.publish("airspeed_kph",{640.0+std::sin(t*.12)*18.0,"km/h",true});bus.publish("hydraulic_pressure_pct",{94.0+std::sin(t*.19)*2.0,"%",true});bus.publish("fuel_level_pct",{78.0-t*.002,"%",true});
 bus.publish("jet_engine_core_pct",{72.0+std::sin(t*.23)*2.0,"%",true});bus.publish("turboprop_torque_pct",{68.0+std::sin(t*.17)*3.0,"%",true});bus.publish("prop_rpm_pct",{96.0+std::sin(t*.15)*1.2,"%",true});bus.publish("rotor_rpm_pct",{100.0+std::sin(t*.21)*.8,"%",true});bus.publish("battery_soc_pct",{std::max(0.0,94.0-t*.003),"%",true});bus.publish("link_quality_pct",{97.0+std::sin(t*.13),"%",true});bus.publish("nav_quality_pct",{98.0+std::sin(t*.09)*.8,"%",true});
 faults.clear();switch(kind_){case ScenarioKind::Nominal:break;case ScenarioKind::PowerTransient:if(clock.tick()>=15&&clock.tick()<=35)faults.set({"scenario-power","bus_voltage_v",FaultMode::Override,20.8,true});break;case ScenarioKind::SensorDropout:if(clock.tick()>=12&&clock.tick()<=28)faults.set({"scenario-imu","imu_pitch_deg",FaultMode::Invalidate,0.0,true});break;case ScenarioKind::ThermalRise:if(clock.tick()>=10)faults.set({"scenario-thermal","cpu_temp_c",FaultMode::Offset,static_cast<double>(clock.tick()-9)*1.4,true});break;}faults.apply(bus);}
std::vector<std::string> ScenarioEngine::names(){return{"nominal","power-transient","sensor-dropout","thermal-rise"};}
ScenarioKind ScenarioEngine::fromName(const std::string& n){if(n=="nominal")return ScenarioKind::Nominal;if(n=="power-transient")return ScenarioKind::PowerTransient;if(n=="sensor-dropout")return ScenarioKind::SensorDropout;if(n=="thermal-rise")return ScenarioKind::ThermalRise;throw std::invalid_argument("unknown scenario: "+n);}
const char* ScenarioEngine::toString(ScenarioKind k){switch(k){case ScenarioKind::Nominal:return"NOMINAL";case ScenarioKind::PowerTransient:return"POWER TRANSIENT";case ScenarioKind::SensorDropout:return"SENSOR DROPOUT";case ScenarioKind::ThermalRise:return"THERMAL RISE";}return"UNKNOWN";}
} // namespace nexvary::avionics
