#include "app/AvionicsLab.hpp"
#include "app/ConsoleCockpit.hpp"
#include "config/RunProfile.hpp"
#include "io/SessionArchive.hpp"
#include "report/LabReport.hpp"
#include "sim/ScenarioEngine.hpp"
#include <CLI/CLI.hpp>
#include <chrono>
#include <exception>
#include <iostream>
#include <string>
using namespace nexvary::avionics;
int main(int argc,char**argv){CLI::App app{"NEXVARY Avionics Lab — training/simulation only"};app.set_version_flag("--version","NEXVARY Avionics Lab 0.11.0");std::string scenarioName="nominal",profilePath,exportPath,inspectPath,reportJson,reportMd;int ticks=40,stepMs=100;bool replay=false,list=false;auto*scenarioOpt=app.add_option("--scenario",scenarioName,"Synthetic scenario");auto*ticksOpt=app.add_option("--ticks",ticks,"Simulation ticks")->check(CLI::Range(1,100000));auto*stepOpt=app.add_option("--step-ms",stepMs,"Simulation step milliseconds")->check(CLI::Range(10,10000));app.add_option("--profile",profilePath,"JSON training run profile");app.add_flag("--replay",replay,"Replay summaries");app.add_flag("--list-scenarios",list,"List scenarios");app.add_option("--export-json",exportPath,"Export JSON training session");app.add_option("--inspect-json",inspectPath,"Inspect JSON training session");app.add_option("--report-json",reportJson,"Write verification report as JSON");app.add_option("--report-md",reportMd,"Write verification report as Markdown");CLI11_PARSE(app,argc,argv);try{if(!profilePath.empty()){auto p=RunProfile::readFile(profilePath);if(scenarioOpt->count()==0)scenarioName=p.scenario;if(ticksOpt->count()==0)ticks=p.ticks;if(stepOpt->count()==0)stepMs=p.stepMs;if(exportPath.empty())exportPath=p.exportSession;if(reportJson.empty())reportJson=p.reportJson;if(reportMd.empty())reportMd=p.reportMarkdown;}if(list){for(const auto&n:ScenarioEngine::names())std::cout<<n<<'\n';return 0;}if(!inspectPath.empty()){auto d=SessionArchive::readFile(inspectPath);std::cout<<"SESSION schema="<<d.schema<<" scenario="<<d.scenario<<" frames="<<d.frames.size()<<" events="<<d.events.size()<<'\n';return 0;}AvionicsLab lab(ScenarioEngine::fromName(scenarioName));LabSnapshot last;for(int i=0;i<ticks;++i)last=lab.step(std::chrono::milliseconds{stepMs});ConsoleCockpit::render(std::cout,last);std::cout<<" RECORDED FRAMES: "<<lab.recorder().size()<<" | EVENT COUNT: "<<lab.eventLog().size()<<"\n";if(replay){ReplayCursor c(lab.recorder());std::size_t count=0;while(auto f=c.next()){if(count%10==0||!c.hasNext())std::cout<<" REPLAY seq="<<f->sequence<<" time_ms="<<f->simTime.count()<<" sensors="<<f->sensors.size()<<'\n';++count;}}if(!exportPath.empty()){SessionArchive::writeFile(exportPath,scenarioName,lab.recorder(),lab.eventLog());std::cout<<" SESSION EXPORTED: "<<exportPath<<'\n';}auto report=LabReport::analyze(scenarioName,lab.recorder(),lab.eventLog());if(!reportJson.empty())LabReport::writeJson(reportJson,report);if(!reportMd.empty())LabReport::writeMarkdown(reportMd,report);return 0;}catch(const std::exception&ex){std::cerr<<"error: "<<ex.what()<<'\n';return 1;}}
